In [3]:
import pandas as pd
import numpy as np

In [24]:
#ARRAYS CON PYTHON
import array as arr
a = arr.array('i', [1, 2, 3, 4, 5])
for i in a:
    print(i)

1
2
3
4
5


In [23]:
#array de textos
array_texto = arr.array('u', ['a', 'b', 'c', 'd', 'e'])
print(array_texto)

array('u', 'abcde')


In [19]:
lista = [1, 2, 3, 4, 5,6]
serie = pd.Series(lista)
print(serie)
print(serie.shape)
print(serie[0:1])  # Acceder al primer elemento de la serie

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64
(6,)
0    1
dtype: int64


In [7]:
print(lista)

[[1, 2], [3, 4], [5, 6]]


In [13]:
#array de 3 dimensiones con numpy
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(array_3d)
print(array_3d.shape)   

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


In [26]:
#array con numpy
matriz = np.array([1,2,3,4,5,6,7,8])
print(matriz)

[1 2 3 4 5 6 7 8]


In [30]:
lista = [1,2,3,4,5,6]
matriz = np.array([1,2,3,4,5,6])
lista.append(7)
print(lista)
matriz = np.append(matriz, 7)
print(matriz)


[1, 2, 3, 4, 5, 6, 7]
[1 2 3 4 5 6 7]


In [33]:
#operaciones con matrices
a = np.array([1,3,5])
b = np.array([2,4,6])
suma = a / b
print(suma) 

[0.5        0.75       0.83333333]


In [38]:
#matriz 2 dimensiones numpy
m2d = np.array([[1,2,3],[4,5,6]])
print(m2d)
print(m2d.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [39]:
#Matriz de 3 X 3
lista = [[1,2,3],[4,5,6],[7,8,9]]
matriz_3x3 = np.array(lista)
print(matriz_3x3)
print(matriz_3x3.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [48]:
m = np.arange(20).reshape(10,2)
print(m)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [53]:
m = np.arange(20).reshape(4,5)
print(m.shape)
print(m.ndim)
print(m.size)
print(m)

(4, 5)
2
20
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [55]:
matrizZeros = np.zeros((3,4))
print(matrizZeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [56]:
matriz2 = np.arange(10)
print(matriz2)

[0 1 2 3 4 5 6 7 8 9]


In [61]:
matriz3 = np.linspace(99,88,25)
print(matriz3.size)
print(matriz3.ndim)
print(matriz3.shape)
print(matriz3)

25
1
(25,)
[99.         98.54166667 98.08333333 97.625      97.16666667 96.70833333
 96.25       95.79166667 95.33333333 94.875      94.41666667 93.95833333
 93.5        93.04166667 92.58333333 92.125      91.66666667 91.20833333
 90.75       90.29166667 89.83333333 89.375      88.91666667 88.45833333
 88.        ]


In [62]:
matriz4 = np.arange(24).reshape(2,3,4)
print(matriz4.size)
print(matriz4)

24
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [68]:
m5 = np.array([5,6,3,4,8,90])
print(np.sort(m5))
print(np.power(m5,3))

[ 3  4  5  6  8 90]
[   125    216     27     64    512 729000]


In [69]:
print(np.array(m5**2))

[  25   36    9   16   64 8100]


In [77]:
print(np.array(m5 >= 10))

[False False False False False  True]


In [80]:
print(np.array(m5.min()))

3


In [81]:
m1 = np.array([2,3,4,5,6,7])
m2 = np.array([11,34,67,99])

print(np.concatenate((m1,m2)))

[ 2  3  4  5  6  7 11 34 67 99]


In [90]:
m1 = np.array([[1,2],[3,4]])
m2 = np.array([[5,6],[7,8]])

print(m1+m2)
print()
print(m1 + 2)
print()
print(np.add(m1,m2))
print()
print(np.subtract(m1,m2))
print()
print(np.divide(m1,m2))
print()
print(m1.dot(m2))



[[ 6  8]
 [10 12]]

[[3 4]
 [5 6]]

[[ 6  8]
 [10 12]]

[[-4 -4]
 [-4 -4]]

[[0.2        0.33333333]
 [0.42857143 0.5       ]]

[[19 22]
 [43 50]]


In [103]:
#Numero aleatorios
m = np.random.randint(10,size=(3,3))
print(m.size)
print(m)


9
[[7 6 4]
 [1 5 3]
 [3 6 2]]


In [110]:
n1 = np.random.rand(4)
n2 = np.random.rand(2,2)
print(n1)
print(n2)

[0.63000095 0.1246981  0.00415043 0.22530202]
[[0.20692851 0.95023542]
 [0.3126561  0.58129095]]


In [ ]:
n3 = np.random.choice([3,5,9,5,1],size=(2,3))
print(n3)

[[1 1 1]
 [5 5 3]]


In [132]:
matrizEjemplo = np.random.choice([4,2,8,10],p=[0.3,0.5,0.1,0.1],size=[50])
print(matrizEjemplo)
print(matrizEjemplo.size)

[ 4 10  2  2 10  2  8  4  2  4  4 10  2  2  2  2  2  8  2  2  2  8  4  2
  4  4  4  4  4  2  2  8  2  2 10  2  2  2  2  2  2  2 10  4  2  2  2  2
  2  2]
50


In [135]:
#coordenas Ejes a las matrices
matrizejes = np.random.randint(20,size=(2,3))
print(matrizejes)
#Coordenadas (matriz, filas, Colunmas)

[[ 6  4 16]
 [18  8 16]]


In [141]:
#sumas
print(np.sum(matrizejes, axis=0))


[24 12 32]


In [145]:
m1 = np.array([[1,2],[3,4]])
m2 = np.array([[5,6],[7,8]])

print(m1)
print()
print(m2)
print()
print(np.concat([m1,m2],axis=0))
print()
print(np.concat([m1,m2],axis=1))

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2 5 6]
 [3 4 7 8]]


In [151]:
#funciones estadisticas con nympy
m1 = np.random.randint(9,size=(3,3))
print(m1)
print()
print(np.amax(m1))
print()
print(np.amin(m1))
print()
print(np.amax(m1,axis=0))
print()
print(np.amax(m1,axis=1))

[[6 2 7]
 [3 7 2]
 [3 8 8]]

8

2

[6 8 8]

[7 7 8]


In [156]:
print(np.ptp(m1))
print()
print(np.percentile(m1,50,axis=1))

6

[6. 3. 8.]


In [157]:
#recorrer matriz de dos dimensiones
for fila in m1:
    for elemento in fila:
        print(elemento, end=" ")




6 2 7 3 7 2 3 8 8 

In [161]:
print(np.mean(m1,axis=0))
print()
print(np.median(m1,axis=1))

[4.         5.66666667 5.66666667]

[6. 3. 8.]


In [167]:
m1D = np.array([2,4,3,7,4,8])
print(m1D)
print()
print(np.average(m1D))
print()
print(np.average(m1D,axis=0))
print()
print(np.std(m1D))


[2 4 3 7 4 8]

4.666666666666667

4.666666666666667

2.1343747458109497


In [175]:
#Algebra Lineal
m = np.array([[1,-1,2],[3,2,0]])
print(m)
print()
print(m.T)

print()
m1 = np.array([[1],[2],[3]])
print(m1)
print()
print(np.transpose(m1))



[[ 1 -1  2]
 [ 3  2  0]]

[[ 1  3]
 [-1  2]
 [ 2  0]]

[[1]
 [2]
 [3]]

[[1 2 3]]


In [ ]:
# operaciones con matrices
m1 = np.array([[2,1,-2],[3,0,1],[1,1,-1]])
print(m1)
print()
m2 = np.array([[-3],[5],[-2]])
print(np.transpose(m2))
print()

x = np.linalg.solve(m1,m2)

print(x)


[[ 2  1 -2]
 [ 3  0  1]
 [ 1  1 -1]]

[[-3  5 -2]]

[[ 1.]
 [-1.]
 [ 2.]]


In [ ]:
print(np.transpose(m2).)