### NUMPY

In [22]:
import pandas as pd
import numpy as np

In [8]:
#arrecho 1 dimension y 5 elementos
arr1 = np.array([1, 2, 3, 4, 5])
print(f'Arreglo 1D: {arr1}')
print(f'Forma(shape): {arr1.shape}')
print(f'Tipo de datos (dtype): {arr1.dtype}')

Arreglo 1D: [1 2 3 4 5]
Forma(shape): (5,)
Tipo de datos (dtype): int64


In [9]:
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(f'Arreglo 2D: {arr2}')
print(f'Forma(shape): {arr2.shape}')
print(f'Tipo de datos (dtype): {arr2.dtype}')

Arreglo 2D: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Forma(shape): (2, 5)
Tipo de datos (dtype): int64


In [10]:
A, B = 3, 4
arr3 = np.zeros((A, B))

In [11]:
print(arr3)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
arr_aleatorio = np.random.rand(4,4)
print(arr_aleatorio)

[[0.44338769 0.91955929 0.97600071 0.4879207 ]
 [0.05908318 0.8188898  0.98905268 0.02110665]
 [0.99592552 0.4599563  0.9532457  0.52313964]
 [0.18823822 0.9965561  0.19908968 0.24851631]]


In [17]:
arrAleEnteros = np.random.randint(1, 10, size=(8))
# print(arrAleEnteros)
arrAleEnteros

array([1, 3, 7, 8, 7, 9, 5, 5])

In [23]:
s = np.random.randint(0, 7, size=10)
pd.Series(s)

0    2
1    2
2    0
3    0
4    1
5    6
6    0
7    6
8    2
9    4
dtype: int64

In [25]:
arrAleatorio3x4 = np.random.rand(3,4)
print(arrAleatorio3x4)

[[0.17513723 0.12117125 0.96714979 0.60667653]
 [0.40881793 0.6321107  0.90921025 0.18863656]
 [0.12655591 0.00692463 0.7317152  0.68990199]]


In [29]:
#crear arreglo con una lista
lista = [[1, 2, 3, 4, 5],[4,7,5,6,2],[4,2,5,7,8]]
arrDesdeLista = np.array(lista)
print(arrDesdeLista)

[[1 2 3 4 5]
 [4 7 5 6 2]
 [4 2 5 7 8]]


In [30]:
arraCeros = np.zeros((8,9))
print(arraCeros)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [32]:
#arreco con 1 2X2
arrUnos = np.ones((2,2))
print(arrUnos)

[[1. 1.]
 [1. 1.]]


In [34]:
arrUnos[:1]

array([[1., 1.]])

In [37]:
arr4 = np.array([[1,2,3],[4,5,6]])
print(arr4)

[[1 2 3]
 [4 5 6]]


In [45]:
print(arr4[0,2])

3


In [42]:
print(arr4[:1])

[[1 2 3]]


In [48]:
print(arr4[0,:])

[1 2 3]


In [49]:
print(arr4[:,1])

[2 5]


In [51]:
#Matriz identidad
matrizIdentidad = np.eye(4)
print(matrizIdentidad)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [53]:
#matriz de mas de 2 dimensiones (Matriz, Fila , Columa)
arr5 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr5.shape)

(2, 2, 3)


In [2]:
for i in range(1,10):
    print(i)

1
2
3
4
5
6
7
8
9
